---
title: "Seasonal Adaptation"
author: \emph{Thomas O'Leary, Csenge Petak, Alison Hall}
date: "11/23/2019"
output: pdf_document
bibliography: refs.bib
header-includes:
   - \usepackage{graphicx}
---


# Abstract


# Introduction
Something about an orchard in Pennsylvania [@Bergland2014]. As an example of how to cite.

# Methods


\begin{table}[t]
\centering
\resizebox{\textwidth}{!}{%
\begin{tabular}{|l|l|}
\hline
Parameters                       &      \\ \hline
Crossover probability            & 0.05 \\ \hline
Mutation probability             & 10   \\ \hline
Population size                  & 500  \\ \hline
Number of loci                   & 100  \\ \hline
Exponent of the fitness function & 1    \\ \hline
Dominance                        & 0.5  \\ \hline
Years                            & 100  \\ \hline
Generations per year             & 20   \\ \hline
Seasonal balance                 & 2    \\ \hline
\end{tabular}%
}
\caption{The default parameters that were used for each simulation.}
\label{tab:my-table}
\end{table}

| Parameters                       |      |
|----------------------------------|------|
| Crossover probability            | 0.05 |
| Mutation probability             | 10   |
| Population size                  | 500  |
| Number of loci                   | 100  |
| Exponent of the fitness function | 1    |
| Dominance                        | 0.5  |
| Years                            | 100  |
| Generations per year             | 20   |
| Seasonal balance                 | 2    |

# Results


# Discussion


# References

