---
title: "Outline"
author: "Thomas O'Leary, Csenge Petak, Alison Hall"
date: "11/22/2019"
output: pdf_document
---
**Abstract** 

The abstract will introduce the paper by Wittman et al. that instigated this 
study. They present a term called "segregation lift" which describes 
instances of seasonal allele-fluctuations which may maintain genetic diversity. 
Wittman et al., build a model that exhibits how allelic dominance changes according to the season in a diploid organism to account for different seasonal life-history strategies. The authors present the parameter d, a dominance metric which enciroporates fitness with the seasonal score to allow the dominance to be tracked as it fluctuates according to season. Wittman et al. conclude that d must be greater than 0.5 allows for a "beneficial reversal of dominance" in which heterozygous intermediates are more fit. 

Also present hypothesis here and main results



**Introduction**

Quantitative genetic theory suggests that plasticity occurs in response to selective pressure exerted by environmental heterogeneity (cooper).  Phenotypic plasticity is especially beneficial in variable environments because genetic variability allows for adaptation to changing conditions (Gulisija). Fluctuating selection can maintain polymorphisms in seasonal environments if strong selective pressure towards both homozygous genotypes varies seasonally (novak, bergland). Understanding the role of seasonality on adaptation can allow more accurate predictions to be made about the capacity for organisms to adapt to climate change conditions (fournier-level). 
  There has been some debate regarding whether balancing selection is capable of maintaining genetic polymorphisms in highly variable environments, and it is often thought that  (Asthana, Hedrick). However a study by Bergland et al (2014) observing Drosophila melanogaster in a temperate Pennsyvanian orchard revealed that strong seasonal selection can drive balancing selection favoring different life history traits over a short time span. These results suggest that seasonal variation contributes to the maintenance of two alleles to be present at the same loci long-term.  
  Wittmann et al, (2017) created a model building from Bergland et al to clarify the role of seasonal selection plays in maintaining multilocus polymorphisms. This model introduces the term “segregation lift” which considers the importance of dominance in maintaining polymorphism across many loci in the genome.



- Begin by introducing why we should care about environmental fluctuation and seasonal fitness, how that is projected to grow more and more extreme, and how this study fits into that concept (importance of genetic diversity)
  -seasonal fluctuation has been shown to maintain polymorphisms, but hoe often is this really able to occur. 
  -"marginal overdominance occurs when when the heterozygote has the highest geometric mean fitness, though in one particular generation the homozygote may be most fit" (witt), and seasonal fluctuations are capable of maintaining these advantages (novak)This novak paper found that linkage disequilibrium was required to maintain genetic polymorphims though
- How this study fits into/differs from research of dominance/heterozygote advantage (clarify this)
- Describe the original concept of seasonal selection in more detail. 
- Present seasonal score  
- Introduce why we changed the parameters that we changed, and how we predicted that segregation lift would be affected. (seasonal score, dominance, generations, population size, y fitness exponent, L loci )

**Methods** 


**Results**
Figure 1: Loci specific allele frequencies over time. 
  We have a preliminary version of this graph created and it shows how the frequency of a seasonal allele changes over generations at d=0.5, which suggests that d=0.5 may be sufficient to maintain polymorphism. 
  we plan to run the model over break and change parameters to try to detect how they affect seasonal switches in dominance 

  
Figure 2: A graph encorporating fitness fluctuations?
  

**Conclusion**

We will interpret the results here!
How does this fit into the broader research

