---
title: "Seasonal Adaptation Modeling"
author: "Alison Hall, Csenge Petak, & Thomas O'Leary"
date: "10/30/2019"
output: pdf_document
bibliography: refs.bib
biblio-style: science
---

## Brief Proposal

Seasonal changes in allele frequency has been observed experimentally in a population of _Drososphila melanagaster_ over the course of three years in an orchard in Pennsylvania [@Bergland2014]. This seasonally fluctuating selection leads to a balanced polymorphism which is one possible mechanism for maintaining genetic diversity over time. It was proposed that the alleles that are under seasonal selection have been maintained for millenia. We thought that modeling these dynamics would be provide insight into the mechanisms involved and the extent to which seasonal selection is capable of maintaining these balanced polymorphisms in the population. Or does the model have to include more complicated features like epistasis and linkage.

We hope to build upon the model developed by @Bergland2014. Their model relies upon a mechanishm they call "segregation lift," which necessary "requires seasonal changes in dominance, a phenomenon that may arise naturally in situations with antagonistic pleiotropy and seasonal changes in the relative importance of traits for fitness" [@Wittmann2017]. We want to try to fully understand their model and develop something that may incorporate new variables such as linkage.

Perhaps incorporating looking at seasonal adaptation in other model species such as Copepods. It would be great to do because Melissa would then like the project. Github is not fun!

--

# References


